# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
     - 'PRODUCTION*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy public_html
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzur # --delete # don't delete
        path: code/public_html/
        remote_path: ${{ secrets.APPPATH }}/public_html
        remote_host: ${{ secrets.HOST }}
        remote_user: github
        remote_key: ${{ secrets.GITHUBUSERKEY }}
    
    - name: Deploy flask
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzur # --delete # don't delete
        path: code/flask/
        remote_path: ${{ secrets.APPPATH }}/flask
        remote_host: ${{ secrets.HOST }}
        remote_user: github
        remote_key: ${{ secrets.GITHUBUSERKEY }}
      
    - name: Restart Flask
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: github
        key: ${{ secrets.GITHUBUSERKEY }}
        port: ${{ secrets.SSHPORT }}
        script: |
          sudo rm -rf ${{ secrets.LOGPATH }}/flask.log && sudo rm -rf ${{ secrets.LOGPATH }}/flask_err.log
          sudo systemctl daemon-reload
          sudo systemctl restart playsync
          sudo systemctl restart nginx
